Adds documentation for running a distributed CPU training job using a Kubernetes cluster
dmsuehir/transformers pull request #1
Opened 2023-11-15 20:43 UTC by dmsuehir

This is a placeholder PR with a draft of documentation.

2023-11-16 06:51 UTC, ashahba requested changes
Thanks Dina!
This is a good start.
My comments are mostly minor.

2023-11-16 06:51 UTC, ashahba commented on docs/source/en/perf_train_cpu_many_k8s.md
> +This guide assume that you already have a Kubernetes clusters with multiple CPUs that will be used to run the
`clusters` -> `cluster`

2023-11-16 06:51 UTC, ashahba commented on docs/source/en/perf_train_cpu_many_k8s.md
> +distributed training job. Use `kubectl get nodes` to see a list the nodes that are available on your cluster. Before
`to see a list the nodes` -> `to see a list of the nodes`

2023-11-16 06:51 UTC, ashahba commented on docs/source/en/perf_train_cpu_many_k8s.md
> +distributed training job. Use `kubectl get nodes` to see a list the nodes that are available on your cluster. Before
I'd also add a note here that:
```
I'd add a note here and before asking user to run `kubectl get nodes` like this:
```
If Role-based access control (RBAC) enabled on the cluster, listing nodes and many other cluster wide commands, require specific roles to be granted to the user.```
```

2023-11-16 06:51 UTC, ashahba commented on docs/source/en/perf_train_cpu_many_k8s.md
> +`kubectl get crd` and ensure that the output includes `pytorchjob.kubeflow.org` like the sample output below:
Or maybe reword it like:
use `kubectl get crd pytorchjobs.kubeflow.org` and verify the output is similar to:

2023-11-16 06:51 UTC, ashahba commented on docs/source/en/perf_train_cpu_many_k8s.md
> +-->
Sounds good and I can work on those Dockerfiles.

2023-11-16 06:51 UTC, ashahba commented on docs/source/en/perf_train_cpu_many_k8s.md
> +<!-- TODO: What would it look like if a cloud storage bucket was being used instead? -->
I can fill this.
I need to get a s3 bucket going and do a PoC.

2023-11-16 06:51 UTC, ashahba commented on docs/source/en/perf_train_cpu_many_k8s.md
> +For a more detailed example, out this [blog post (TBD)](TBD) that uses a Kubernetes cluster to fine tune
`out this` -> `checkout this`

2023-11-16 17:40 UTC, ashahba commented on docs/source/en/perf_train_cpu_many_k8s.md
> +-->
In that case, things could get complicated and basically available commands to the user are unknown.
I think the best way to get around this is to mention that:
Please consult cluster admin to get a list of nodes available to the user's group.

2023-11-16 17:41 UTC, ashahba commented on docs/source/en/perf_train_cpu_many_k8s.md
> +-->
In that case, things could get complicated and basically available commands to the user are unknown.
I think the best way to get around this is to mention that:
Please consult cluster admin to get a list of nodes available to the user's group.

2023-11-17 02:03 UTC, dmsuehir commented
@sywangyi This is the PR mentioned in the meeting with documentation for running distributed training on Kubernetes

2023-12-01 21:40 UTC, dmsuehir commented
Closing, since we switched this to e part of the distributed CPU doc instead of a separate doc.

2023-12-01 21:40 UTC, closed without merging